name: Build and Push to Dockerhub

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dockerhub-publish.yml'        
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/api
  DIR_WEBAPP: './'
  
jobs:

  build-push:
    runs-on: ubuntu-latest  # Define a máquina virtual que executará o job

    steps:
    - uses: actions/checkout@v3
   
    - name: Build de imagem
      run: |
        cd ${{ env.DIR_WEBAPP }}
        docker build . --file ./API/Dockerfile --tag ${{ env.IMAGE_DOCKERHUB }}:latest      
   
    - name: Log in Docker Hub - Container Registry
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker tag ${{ env.IMAGE_DOCKERHUB }}:latest ${{ env.IMAGE_DOCKERHUB }}:v${{ github.run_number }}
        docker push --all-tags ${{ env.IMAGE_DOCKERHUB }}
