name: Build and Push to Github

on:
  push:
    branches: [ "main" ]
    #paths:
    #  - '.github/workflows/github-publish.yml'    
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_USER: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.repository_owner }}/api

jobs:

  build-push:
    runs-on: ubuntu-latest  # Define a máquina virtual que executará o job

    steps:
    - uses: actions/checkout@v3
   
    - name: Docker build
      run: |
        docker build . --file ./API/Dockerfile --tag ${{ env.IMAGE_NAME }}:latest     

    - name: Log in to GitHub - Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.GITHUB_USER }}
        password: ${{ secrets.GYTHUB_PAT }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./API/Dockerfile
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
