name: Build and Push to Github

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/github-publish.yml'    
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_DOCKERHUB: mregis/api
  DIR_WEBAPP: './'    

jobs:

  build-push:
    runs-on: ubuntu-latest  # Define a máquina virtual que executará o job

    steps:
    - uses: actions/checkout@v3

    - name: PreCheck
      run: |
        pwd
        ls    
   
    - name: Build de imagem
      run: |
        docker build . --file ./API/Dockerfile --tag ${{ env.IMAGE_DOCKERHUB }}:latest     

    - name: Log in to GitHub - Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker tag ${{ env.IMAGE_DOCKERHUB }}:latest ${{ env.IMAGE_DOCKERHUB }}:v${{ github.run_number }}
        docker push --all-tags ${{ env.IMAGE_DOCKERHUB }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./API/Dockerfile
        push: true
        tags: ghcr.io/mauroregis/api:latest
