name: Build and Push to Github

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github//workflows/github-publish.yml'    
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/api
  DIR_WEBAPP: './'    

jobs:

  build-push:
    runs-on: ubuntu-latest  # Define a máquina virtual que executará o job

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Usa a ação para fazer checkout do código

    - name: Build de imagem
      run: |
        cd ${{ env.DIR_WEBAPP }}
        docker build . --file ./API/Dockerfile --tag ${{ env.IMAGE_DOCKERHUB }}:latest    

    - name: Log in to GitHub - Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./API
        file: ./API/Dockerfile
        push: true
        tags: ghcr.io/mauroregis/api:latest
