name: Build and Push to Github

on:
  push:
    branches:
      - main  # Executa o workflow quando há push na branch main
    paths:
      - 'API/**'  # Caminhos que, ao serem modificados, disparam o workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Define a máquina virtual que executará o job

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Usa a ação para fazer checkout do código

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./API
        file: ./API/Dockerfile
        push: true
        tags: ghcr.io/mauroregis/api:latest
